<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Fri Jan 17 19:44:24 CET 2014.
 */

/**
 * Version information implementation class.
 */
class Weekly_Version extends Weekly_Base_Version
{
    // custom enhancements can go here
}
