<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Configuration handler implementation class.
 */
class Weekly_Form_Handler_Admin_Config extends Weekly_Form_Handler_Admin_Base_Config
{
    // feel free to extend the base handler class here
}
