<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the weekly_user_edit() function.
 * It aims on the manager object type.
 */
class Weekly_Form_Handler_User_Manager_Edit extends Weekly_Form_Handler_User_Manager_Base_Edit
{
    // feel free to extend the base handler class here
}
