<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This is the Admin api helper class.
 */
class Weekly_Api_Base_Admin extends Zikula_AbstractApi
{
    /**
     * Returns available admin panel links.
     *
     * @return array Array of admin links.
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'main'),
                             'text' => $this->__('Frontend'),
                             'title' => $this->__('Switch to user area.'),
                             'class' => 'z-icon-es-home');
        }

        $controllerHelper = new Weekly_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'admin', 'action' => 'getlinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);

        if (in_array('event', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Event:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'event')),
                             'text' => $this->__('Events'),
                             'title' => $this->__('Event list'));
        }
        if (in_array('manager', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Manager:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'manager')),
                             'text' => $this->__('Managers'),
                             'title' => $this->__('Manager list'));
        }
        if (in_array('comanager', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Comanager:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'comanager')),
                             'text' => $this->__('Comanagers'),
                             'title' => $this->__('Comanager list'));
        }
        if (in_array('kind', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Kind:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'kind')),
                             'text' => $this->__('Kind'),
                             'title' => $this->__('Kind list'));
        }
        if (in_array('location', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Location:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'location')),
                             'text' => $this->__('Locations'),
                             'title' => $this->__('Location list'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'config'),
                             'text' => $this->__('Configuration'),
                             'title' => $this->__('Manage settings for this application'));
        }

        return $links;
    }
}
