<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Relation selector plugin implementation class.
 */
class Weekly_Form_Plugin_RelationSelectorList extends Weekly_Form_Plugin_Base_RelationSelectorList
{
    // feel free to add your customisation here
}
