<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Installer base class.
 */
class Weekly_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the Weekly application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // Check if upload directories exist and if needed create them
        try {
            $controllerHelper = new Weekly_Util_Controller($this->serviceManager);
            $controllerHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            return LogUtil::registerError($e->getMessage());
        }
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        // set up all our vars with initial values
        $this->setVar('pageSize', 20);
        $this->setVar('pictureSize', 102400);
        $this->setVar('showManager', true);
        $this->setVar('showComanager', true);
        $this->setVar('showKind', true);
        $this->setVar('showLocation', true);
        $this->setVar('showParticipants', true);
        $this->setVar('maxParticipantsDefault', 0);
        $this->setVar('allowDeactivating', false);
    
        $categoryRegistryIdsPerEntity = array();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the Weekly application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while updating tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall Weekly.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove all module vars
        $this->delVars();
    
        // remove all thumbnails
        $manager = $this->getServiceManager()->getService('systemplugin.imagine.manager');
        $manager->setModule($this->name);
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = FileUtil::getDataDirectory() . '/' . $this->name . '/';
        LogUtil::registerStatus($this->__f('The upload directories at [%s] can be removed manually.', $uploadPath));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for Weekly.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'Weekly_Entity_Event';
        $classNames[] = 'Weekly_Entity_Manager';
        $classNames[] = 'Weekly_Entity_Comanager';
        $classNames[] = 'Weekly_Entity_Kind';
        $classNames[] = 'Weekly_Entity_Location';
    
        return $classNames;
    }
    
    /**
     * Create the default data for Weekly.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'Weekly_Entity_Event';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'Weekly_Entity_Manager';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'Weekly_Entity_Comanager';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'Weekly_Entity_Kind';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'Weekly_Entity_Location';
        $this->entityManager->getRepository($entityClass)->truncateTable();
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('Weekly', 'api.method_not_found', array('Weekly_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'core.preinit', array('Weekly_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'core.init', array('Weekly_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'core.postinit', array('Weekly_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'controller.method_not_found', array('Weekly_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> Weekly_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('Weekly', 'frontcontroller.predispatch', array('Weekly_Listener_FrontController', 'preDispatch'));
    
        // installer -> Weekly_Listener_Installer
        EventUtil::registerPersistentModuleHandler('Weekly', 'installer.module.installed', array('Weekly_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'installer.module.upgraded', array('Weekly_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'installer.module.uninstalled', array('Weekly_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'installer.subscriberarea.uninstalled', array('Weekly_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> Weekly_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('Weekly', 'module_dispatch.postloadgeneric', array('Weekly_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module_dispatch.preexecute', array('Weekly_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module_dispatch.postexecute', array('Weekly_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module_dispatch.custom_classname', array('Weekly_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module_dispatch.service_links', array('Weekly_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> Weekly_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.mailer.api.sendmessage', array('Weekly_Listener_Mailer', 'sendMessage'));
    
        // page -> Weekly_Listener_Page
        EventUtil::registerPersistentModuleHandler('Weekly', 'pageutil.addvar_filter', array('Weekly_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'system.outputfilter', array('Weekly_Listener_Page', 'systemOutputfilter'));
    
        // errors -> Weekly_Listener_Errors
        EventUtil::registerPersistentModuleHandler('Weekly', 'setup.errorreporting', array('Weekly_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'systemerror', array('Weekly_Listener_Errors', 'systemError'));
    
        // theme -> Weekly_Listener_Theme
        EventUtil::registerPersistentModuleHandler('Weekly', 'theme.preinit', array('Weekly_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'theme.init', array('Weekly_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'theme.load_config', array('Weekly_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'theme.prefetch', array('Weekly_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'theme.postfetch', array('Weekly_Listener_Theme', 'postFetch'));
    
        // view -> Weekly_Listener_View
        EventUtil::registerPersistentModuleHandler('Weekly', 'view.init', array('Weekly_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'view.postfetch', array('Weekly_Listener_View', 'postFetch'));
    
        // user login -> Weekly_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.login.started', array('Weekly_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.login.veto', array('Weekly_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.login.succeeded', array('Weekly_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.login.failed', array('Weekly_Listener_UserLogin', 'failed'));
    
        // user logout -> Weekly_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.logout.succeeded', array('Weekly_Listener_UserLogout', 'succeeded'));
    
        // user -> Weekly_Listener_User
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.gettheme', array('Weekly_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.account.create', array('Weekly_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.account.update', array('Weekly_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.account.delete', array('Weekly_Listener_User', 'delete'));
    
        // registration -> Weekly_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.registration.started', array('Weekly_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.registration.succeeded', array('Weekly_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.ui.registration.failed', array('Weekly_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.registration.create', array('Weekly_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.registration.update', array('Weekly_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'user.registration.delete', array('Weekly_Listener_UserRegistration', 'delete'));
    
        // users module -> Weekly_Listener_Users
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.users.config.updated', array('Weekly_Listener_Users', 'configUpdated'));
    
        // group -> Weekly_Listener_Group
        EventUtil::registerPersistentModuleHandler('Weekly', 'group.create', array('Weekly_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'group.update', array('Weekly_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'group.delete', array('Weekly_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'group.adduser', array('Weekly_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'group.removeuser', array('Weekly_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> Weekly_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('Weekly', 'get.pending_content', array('Weekly_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('Weekly', 'module.content.gettypes', array('Weekly_Listener_ThirdParty', 'contentGetTypes'));
    }
}
