<?php
/**
 * Weekly.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Weekly
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Fri Jan 17 19:44:24 CET 2014.
 */

/**
 * Version information base class.
 */
class Weekly_Base_Version extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '0.2.2';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Weekly');
        // the module description
        $meta['description']          = $this->__('a module for a weekly rota');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('weekly');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.6'; // not ready for 1.3.7 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true)
/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'Weekly::' => '::',
            'Weekly::Ajax' => '::',
            'Weekly:ItemListBlock:' => 'Block title::',
            'Weekly:Event:' => 'Event ID::',
            'Weekly:Kind:Event' => 'Kind ID:Event ID:',
            'Weekly:Location:Event' => 'Location ID:Event ID:',
            'Weekly:Leader:Event' => 'Leader ID:Event ID:',
            'Weekly:Organisator:Event' => 'Organisator ID:Event ID:',
            'Weekly:Leader:' => 'Leader ID::',
            'Weekly:Organisator:' => 'Organisator ID::',
            'Weekly:Kind:' => 'Kind ID::',
            'Weekly:Location:' => 'Location ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.ui_hooks.events', 'ui_hooks', __('weekly Events Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'weekly.ui_hooks.events.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'weekly.ui_hooks.events.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'weekly.ui_hooks.events.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'weekly.ui_hooks.events.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'weekly.ui_hooks.events.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'weekly.ui_hooks.events.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'weekly.ui_hooks.events.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.filter_hooks.events', 'filter_hooks', __('weekly Events Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'weekly.filter_hooks.events.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.ui_hooks.leaders', 'ui_hooks', __('weekly Leaders Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'weekly.ui_hooks.leaders.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'weekly.ui_hooks.leaders.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'weekly.ui_hooks.leaders.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'weekly.ui_hooks.leaders.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'weekly.ui_hooks.leaders.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'weekly.ui_hooks.leaders.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'weekly.ui_hooks.leaders.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.filter_hooks.leaders', 'filter_hooks', __('weekly Leaders Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'weekly.filter_hooks.leaders.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.ui_hooks.organisators', 'ui_hooks', __('weekly Organisators Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'weekly.ui_hooks.organisators.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'weekly.ui_hooks.organisators.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'weekly.ui_hooks.organisators.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'weekly.ui_hooks.organisators.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'weekly.ui_hooks.organisators.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'weekly.ui_hooks.organisators.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'weekly.ui_hooks.organisators.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.filter_hooks.organisators', 'filter_hooks', __('weekly Organisators Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'weekly.filter_hooks.organisators.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.ui_hooks.kind', 'ui_hooks', __('weekly Kind Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'weekly.ui_hooks.kind.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'weekly.ui_hooks.kind.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'weekly.ui_hooks.kind.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'weekly.ui_hooks.kind.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'weekly.ui_hooks.kind.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'weekly.ui_hooks.kind.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'weekly.ui_hooks.kind.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.filter_hooks.kind', 'filter_hooks', __('weekly Kind Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'weekly.filter_hooks.kind.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.ui_hooks.locations', 'ui_hooks', __('weekly Locations Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'weekly.ui_hooks.locations.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'weekly.ui_hooks.locations.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'weekly.ui_hooks.locations.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'weekly.ui_hooks.locations.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'weekly.ui_hooks.locations.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'weekly.ui_hooks.locations.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'weekly.ui_hooks.locations.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.weekly.filter_hooks.locations', 'filter_hooks', __('weekly Locations Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'weekly.filter_hooks.locations.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }
}
